### ISSUE TITLE
does not delete any files

### ISSUE THREAD

**Issue by dub4u** [cfbao/google-drive-trash-cleaner#3]
The script does not work for me at all. It does not clean any files. I have tried both under Cygwin and Ubuntu Server environments. I keep getting the same error during the deletion phase:

`googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/0B64QWZulDuUCRUhXMm9KM254VW8? returned "The user does not have sufficient permissions for this file.">`

**Comment by dub4u** [comment]
[This Stackoverflow question](https://stackoverflow.com/questions/32309136/google-drive-api-client-python-insufficient-permission-for-files-insert) might have the answer.

**Comment by cfbao** [comment]
Which version of the script are you using? It seems like you encountered a shared file that's not owned by you. v1.0.1 release doesn't handle this appropriately. It's fixed in v1.1.1rc (or latest commit in master).

Could you try the latest version and let me know the result? Thanks.

_Sent from my Samsung SM-G900W8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dub4u** [comment]
Yes, that's it and that also closes my other two issues!

**Comment by dub4u** [comment]
Thanks for this script by the way! It's very helpful!
