### ISSUE TITLE
Feature request: showing filesize

### ISSUE THREAD

**Issue by AlexDings** [cfbao/google-drive-trash-cleaner#6]
I love this tool and it is really efficient. Even if you just want to clean out your complete trash folder.

One feature I would love to see is how much data was deleted at the end of the end of the clean.

**Comment by cfbao** [comment]
It's doable, but would probably come with a drop in efficiency, especially if there are large trashed folders.

Because Google Drive doesn't provide folder sizes, we'd have to go into a folder (and subfolders) and go through all files contained within to do a proper size calculation. This could take many API calls. I do have a private script for folder size calculation, but it's fragile and not ready for release, and indeed slow (for large folders).

Still, yes, I can try implementing this when I have some free time.

**Comment by cfbao** [comment]
Project deprecated. See [ReadMe](https://github.com/cfbao/google-drive-trash-cleaner/blob/master/README.md).
